#Requires -Version 5.1
<#
.SYNOPSIS
    Generates a release keystore for WiseTVPlayer and writes android/key.properties.

.DESCRIPTION
    - Creates the keystore directory if it does not exist.
    - Runs keytool (from JDK/Android Studio) to generate a new RSA-2048 key.
    - Writes android/key.properties with the chosen values.

    You will be prompted interactively for passwords so they are never stored
    in this script or in shell history.

.EXAMPLE
    .\scripts\generate_keystore.ps1
    .\scripts\generate_keystore.ps1 -Alias myapp -ValidityYears 50
#>
param(
    [string] $Alias        = 'wisetv',
    [int]    $ValidityYears = 25
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Resolve project root ──────────────────────────────────────────────────────
$scriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectDir = Split-Path -Parent $scriptDir
$keystoreDir = Join-Path $projectDir 'keystore'
$keystorePath = Join-Path $keystoreDir 'wisetv-release.jks'
$keyPropsPath = Join-Path $projectDir 'android\key.properties'

# ── Find keytool ──────────────────────────────────────────────────────────────
$keytool = $null
foreach ($candidate in @(
    (Get-Command keytool -ErrorAction SilentlyContinue)?.Source,
    "$env:JAVA_HOME\bin\keytool.exe",
    "$env:ANDROID_HOME\jdk\bin\keytool.exe",
    "C:\Program Files\Android\Android Studio\jbr\bin\keytool.exe",
    "C:\Program Files\Android\Android Studio\jre\bin\keytool.exe"
)) {
    if ($candidate -and (Test-Path $candidate)) { $keytool = $candidate; break }
}
if (-not $keytool) {
    Write-Error "keytool not found. Install a JDK or set JAVA_HOME and retry."
    exit 1
}
Write-Host "Using keytool: $keytool" -ForegroundColor Cyan

# ── Check for existing keystore ───────────────────────────────────────────────
if (Test-Path $keystorePath) {
    $overwrite = Read-Host "Keystore already exists at $keystorePath. Overwrite? [y/N]"
    if ($overwrite -notmatch '^[Yy]') { Write-Host "Aborted."; exit 0 }
}

# ── Gather info ───────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "── Keystore details ─────────────────────────────────────────────" -ForegroundColor Yellow
$dname = Read-Host "Your name or organisation (CN)"
if ([string]::IsNullOrWhiteSpace($dname)) { $dname = 'WiseTVPlayer Developer' }

$storePass = Read-Host "Keystore password (min 6 chars)" -AsSecureString
$storePassPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($storePass))

$keyPass = Read-Host "Key password (Enter = same as keystore password)" -AsSecureString
$keyPassPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($keyPass))
if ([string]::IsNullOrWhiteSpace($keyPassPlain)) { $keyPassPlain = $storePassPlain }

# ── Create keystore directory ─────────────────────────────────────────────────
if (-not (Test-Path $keystoreDir)) {
    New-Item -ItemType Directory -Path $keystoreDir | Out-Null
    Write-Host "Created $keystoreDir" -ForegroundColor Green
}

# ── Generate keystore ─────────────────────────────────────────────────────────
Write-Host ""
Write-Host "Generating keystore…" -ForegroundColor Cyan
& $keytool `
    -genkeypair `
    -v `
    -keystore $keystorePath `
    -alias $Alias `
    -keyalg RSA `
    -keysize 2048 `
    -validity ($ValidityYears * 365) `
    -dname "CN=$dname, O=WiseTVPlayer, C=US" `
    -storepass $storePassPlain `
    -keypass $keyPassPlain

if ($LASTEXITCODE -ne 0) {
    Write-Error "keytool exited with code $LASTEXITCODE"
    exit $LASTEXITCODE
}
Write-Host "Keystore created: $keystorePath" -ForegroundColor Green

# ── Write key.properties ──────────────────────────────────────────────────────
$relativeJks = '..\keystore\wisetv-release.jks'   # relative to android/
$keyPropsContent = @"
# Auto-generated by scripts\generate_keystore.ps1
# Do NOT commit this file.
storeFile=$relativeJks
storePassword=$storePassPlain
keyAlias=$Alias
keyPassword=$keyPassPlain
"@

Set-Content -Path $keyPropsPath -Value $keyPropsContent -Encoding UTF8
Write-Host "Written:  $keyPropsPath" -ForegroundColor Green

# ── Done ──────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "All done! Next:" -ForegroundColor Yellow
Write-Host "  1. Run  scripts\build_release.ps1  to build a signed APK/AAB." -ForegroundColor White
Write-Host "  2. Back up the keystore file OUTSIDE the project repo." -ForegroundColor White
Write-Host "     Losing it means you can never update the app on the Play Store." -ForegroundColor Red
